image: golang:alpine
# services:
#     - docker:dind

# variables:
#     IMAGE_NAME: registry.gitlab.com/hokiegeek/hgtealib:$CI_BUILD_REF_NAME

stages:
    - test
      #     - build_image

before_script:
    - apk add --update git
    - ln -s /builds /go/src/github.com
      #     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

test_job:
    stage: test
    script:
        - go get .
        - go test .

          # build_image_job:
          #     stage: build_image
          #     script:
          #         - docker build -t $IMAGE_NAME .
          #         - docker push $IMAGE_NAME
